apiVersion: v1
kind: Service
metadata:
  name: mess-frontend
  namespace: mess-system
spec:
  selector:
    app: mess-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
